name: Deploy Backend
on:
  push:
    branches:
      - master-backend
jobs:
  copilot:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup AWS Copilot
        uses: softprops/setup-aws-copilot@v1
      - name: Copy Firebase Credentials
        run: |
          echo $FIREBASE_CREDENTIALS >> backend/firebase_credentials.json
        shell: bash
        env:
          FIREBASE_CREDENTIALS: ${{secrets.FIREBASE_CREDENTIALS}}
      - name: Deploy service
        working-directory: ./backend
        run: copilot deploy --force --env prod
        env:
          AWS_REGION: us-east-2
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'